/**
 * This file is necessary because we can't do
 *
 * ```ts
 *  import * as Icons from 'lucide-svelte'
 * ```
 *
 * Because this would import *all* lucide icons,
 * which would increase bundle-size and load many
 * unnecessary icons.
 */

import {
	AlertCircle,
	Activity,
	KeyRound,
	BadgeCheck,
	AtSign,
	Flag,
	Search,
	Shield,
	Cat,
	Dog,
	ArrowDownCircle,
	School,
	GraduationCap,
	Store,
	Building,
	LineChart,
	BarChart4,
	Kanban,
	TrendingUp,
	Video,
	Phone,
	Mic,
	Camera,
	Zap,
	Wifi,
	CircleDollarSign,
	Palette,
	RotateCcw,
	Magnet,
	Monitor,
	Wrench,
	Gem,
	Headphones,
	Gamepad,
	Calculator,
	Database,
	Folder,
	File,
	Download,
	Paperclip,
	Swords,
	Trophy,
	Crown,
	Book,
	Bone,
	Mail,
	Utensils,
	MapPin,
	Bell,
	Bike
} from 'lucide-svelte';

export const icons = [
	{ name: 'AlertCircle', component: AlertCircle },
	{ name: 'Activity', component: Activity },
	{ name: 'KeyRound', component: KeyRound },
	{ name: 'BadgeCheck', component: BadgeCheck },
	{ name: 'AtSign', component: AtSign },
	{ name: 'Flag', component: Flag },
	{ name: 'Search', component: Search },
	{ name: 'Shield', component: Shield },
	{ name: 'Cat', component: Cat },
	{ name: 'Dog', component: Dog },
	{ name: 'ArrowDownCircle', component: ArrowDownCircle },
	{ name: 'School', component: School },
	{ name: 'GraduationCap', component: GraduationCap },
	{ name: 'Store', component: Store },
	{ name: 'Building', component: Building },
	{ name: 'LineChart', component: LineChart },
	{ name: 'BarChart4', component: BarChart4 },
	{ name: 'Kanban', component: Kanban },
	{ name: 'TrendingUp', component: TrendingUp },
	{ name: 'Video', component: Video },
	{ name: 'Phone', component: Phone },
	{ name: 'Mic', component: Mic },
	{ name: 'Camera', component: Camera },
	{ name: 'Zap', component: Zap },
	{ name: 'Wifi', component: Wifi },
	{ name: 'CircleDollarSign', component: CircleDollarSign },
	{ name: 'Palette', component: Palette },
	{ name: 'RotateCcw', component: RotateCcw },
	{ name: 'Magnet', component: Magnet },
	{ name: 'Monitor', component: Monitor },
	{ name: 'Wrench', component: Wrench },
	{ name: 'Gem', component: Gem },
	{ name: 'Headphones', component: Headphones },
	{ name: 'Gamepad', component: Gamepad },
	{ name: 'Calculator', component: Calculator },
	{ name: 'Database', component: Database },
	{ name: 'Folder', component: Folder },
	{ name: 'File', component: File },
	{ name: 'Download', component: Download },
	{ name: 'Paperclip', component: Paperclip },
	{ name: 'Swords', component: Swords },
	{ name: 'Trophy', component: Trophy },
	{ name: 'Crown', component: Crown },
	{ name: 'Book', component: Book },
	{ name: 'Bone', component: Bone },
	{ name: 'Mail', component: Mail },
	{ name: 'Utensils', component: Utensils },
	{ name: 'MapPin', component: MapPin },
	{ name: 'Bell', component: Bell },
	{ name: 'Bike', component: Bike }
];
